# Generated by Django 5.0 on 2024-01-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_video_subtitle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subtitle'),
        ),
    ]
