# Generated by Django 5.0 on 2024-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_video_subtitle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='path_video',
            field=models.FileField(max_length=200, upload_to='Files/'),
        ),
    ]
